"""empty message

Revision ID: 5ec14034edea
Revises: 3671efad67cd
Create Date: 2019-05-19 11:26:36.388285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ec14034edea'
down_revision = '3671efad67cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_photo')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_photo', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
